#version: v2.1.8.{build}
os:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - Win64

install:
  - ps: |
      ./scripts/get.ps1 -branch $env:APPVEYOR_REPO_BRANCH

build_script:
  - ps: |
      Get-Command xmake
      xmake --version
      xmake build --project=core
      .\core\build\xmake.exe --version
      Set-AppveyorBuildVariable -Name XMAKE_PROGRAM_DIR -Value $(Join-Path $(Get-Location) "xmake")
      Copy-Item -Force core\build\xmake.exe $HOME\xmake

after_build:
  - ps: |
      Copy-Item .\core\build\xmake.exe .\xmake
      Copy-Item .\*.md .\xmake
      Compress-Archive -Path .\xmake -DestinationPath .\archive.zip
      Push-AppveyorArtifact .\archive.zip -FileName xmake.zip -DeploymentName "xmake-$($env:PLATFORM)"

test_script:
  - ps: |
      Get-Command xmake
      xmake --version
      xmake lua --verbose --diagnosis tests\test.lua

