#version: v2.1.8.{build}
os:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - Win64

install:
  - ps: |
      Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-Webrequest "https://raw.githubusercontent.com/xmake-io/xmake/dev/scripts/get.ps1" -UseBasicParsing).Content)) -ArgumentList "dev"

build_script:
  - ps: |
      xmake --version
      xmake -P core
      $env:XMAKE_PROGRAM_DIR = Join-Path $(Get-Location) "xmake"
      .\core\build\xmake.exe --version
      Copy-Item -Force core\build\xmake.exe $HOME\xmake

after_build:
  - ps: |
      Copy-Item .\core\build\xmake.exe .\xmake
      Push-AppveyorArtifact .\xmake -FileName xmake.zip -DeploymentName "xmake-$($env:PLATFORM)"

test_script:
  - ps: |
      Get-Command xmake
      xmake --version
      xmake lua -v -D tests\test.lua

