#version: v2.1.8.{build}
os:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - Win64

install:
  - ps: |
      ./scripts/get.ps1 -branch $env:APPVEYOR_REPO_BRANCH

build_script:
  - ps: |
      Get-Command xmake
      xmake --version
      xmake build --project=core
      Set-AppveyorBuildVariable -Name XMAKE_PROGRAM_DIR -Value $(Join-Path $(Get-Location) "xmake")
      .\core\build\xmake.exe --version
      Copy-Item -Force core\build\xmake.exe $(Get-Command xmake).Source

after_build:
  - ps: |
      Copy-Item .\core\build\xmake.exe .\xmake
      Copy-Item .\*.md .\xmake
      Compress-Archive -Path .\xmake -DestinationPath .\archive.zip -CompressionLevel Optimal
      Push-AppveyorArtifact .\archive.zip -FileName xmake.zip -DeploymentName "xmake-$($env:PLATFORM)"

test_script:
  - ps: |
      xmake --version
      Add-AppveyorTest -Name "tests" -Framework "xmake-test" -FileName ./tests/test.lua -Outcome Running
      $time = Measure-Command { 
        $stdout = xmake lua --verbose --diagnosis tests\test.lua 2>&1
        Write-Host $stdout
        $outcome = if ($?) { "Passed" } else { "Failed" }
      }
      Update-AppveyorTest -Name "tests" -Framework "xmake-test" -FileName ./tests/test.lua -Outcome $outcome -Duration $time.TotalMilliseconds -StdOut $stdout

