name: Debian (Mips)

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        arch: [mips, mipsel, mips64, mips64el]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - uses: docker://multiarch/debian-debootstrap:${{matrix.arch}}-stretch
        with:
          args: 'uname -a'

      - uses: docker://multiarch/debian-debootstrap:${{matrix.arch}}-stretch
        with:
          args: >
            bash -c
            "apt update &&
            cd /github/workspace &&
            ./scripts/get.sh __local__ &&
            source ~/.xmake/profile &&
            export XMAKE_ROOT=y &&
            xmake lua -v -D tests/run.lua"
