name: FreeBSD

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:

    runs-on: macos-10.15

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-FreeBSD
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Tests
        uses: vmactions/freebsd-vm@v0.1.6
        with:
          usesh: true
          mem: 4096
          copyback: false
          prepare: pkg install -y curl unzip gmake llvm gsed bash perl5
          run: |
            gmake -j4
            gmake install
            export XMAKE_ROOT=y
            xrepo --version
            xmake lua -v -D tests/run.lua


